@Library('jenkins-common-lib@master') _

pipeline{
    agent any
    tools {
        jdk "openjdk-11"
        maven "mvn-3.6.3"
    }

    environment {
        DOCKER_REPO = "simple-kanban-backend"
    }

    stages {
        stage("Checkout") {
            steps {
                script {
                    CheckoutGit(
                        "https://github.com/YuetChan/simple-kanban",
                        env.GIT_BRANCH,
                        "backend")
                }
            }
        }

        stage("Post-Checkout") {
            steps {
                sh "cp -r ./backend/* ./"
                sh "rm -rf ./backend"
                sh "ls"
            }
        }

        stage("Compile") {
            steps {
                sh "mvn compile"
            }
        }

        stage("Unit test") {
            steps {
                sh "mvn test"
            }
        }

        stage("Build") {
            steps {
                sh "mvn clean package"
            }
        }

        stage("Build and push docker image") {
            steps {
                script {
                    BuildAndPushDockerImage("tycorp/simple-kanban-backend")
                }
            }
        }
    }
}
