pipeline{
  agent any
  tools {
    jdk 'openjdk-11'
    maven 'mvn-3.6.3'
  }

  environment {
    DOCKER_REGISTRY = "docker.io"
    DOCKER_REPO = "tycorp/simple-kanban-apiserver"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout([$class: 'GitSCM', 
          branches: [[name: env.GIT_BRANCH]], 
          doGenerateSubmoduleConfigurations: false, 
          extensions: [[$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [[path: 'apiserver']]]], 
          submoduleCfg: [], 
          userRemoteConfigs: [[url: 'https://github.com/YuetChan/simple-kanban.git']]])
      }
    }

    stage('Post-Checkout') {
      steps {
        sh 'cp -r ./apiserver/* ./'
        sh 'rm -rf ./apiserver'
        sh 'ls'
      }
    }

    stage('Compile') {
      steps {
        sh 'mvn compile'
      }
    }

    stage('Unit test') {
      steps {
        sh 'mvn test'
      }
    }

    stage('Build') {
      steps {
        sh 'mvn clean package'
      }
    }

    stage('Build docker image') {
      steps {
        docker.withRegistry("https://${DOCKER_REGISTRY}", "2b57eec1-d6dc-4e96-ba14-a63ed7166ff4") {
          def customTag = "latest"
          docker.build("${DOCKER_REPO}:${customTag}", "-f Dockerfile .")
        }
      }
    }
    // stage('Build Docker Image') {
    //   steps {
    //     script {
    //       def dockerImage = docker.build("tycorp/simple-kanban-apiserver", "-f ./Dockerfile .")
    //     }
    //   }
    // }
  }
}
