  tools {
    nodejs "node-18.7.0" // define and install Node.js tool
  }

  stages {
    stage('Build') {
      steps {
        sh 'npm install' // install project dependencies using npm
      }
    }
  }
