pipeline{
  agent any
  tools {
    nodejs "node-18.7.0" 
  }

  stages {
    stage("Checkout") {
      steps {
        checkout([$class: "GitSCM", 
          branches: [[name: env.GIT_BRANCH]], 
          doGenerateSubmoduleConfigurations: false, 
          extensions: [[$class: "SparseCheckoutPaths", sparseCheckoutPaths: [[path: "ui"]]]], 
          submoduleCfg: [], 
          userRemoteConfigs: [[url: "https://github.com/YuetChan/simple-kanban.git"]]])
      }
    }

    stage("Post-Checkout") {
      steps {
        sh "cp ./ui/* ./"
        sh "rm -rf ./ui"
        sh "ls"
      }
    }

    stage("Install") {
      steps {
        sh "npm install"
      }
    }

    stage("Unit test") {
      steps {
        sh "npm test"
      }
    }

    stage("Build") {
      steps {
        sh "npm run build"
      }
    }

    
  }
}

